# Numpy

In [1]:
myArray = [1,2,3]

In [9]:
import numpy as np

In [4]:
arr = np.array(myArray)

In [6]:
print(arr)

[1 2 3]


In [8]:
arr

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
matrix = np.array(my_matrix)

In [14]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
print("Rows: ")
for row in my_matrix:
    print(row)
    for item in row:
        print(item)
    

Rows: 
[1, 2, 3]
1
2
3
[4, 5, 6]
4
5
6
[7, 8, 9]
7
8
9


In [19]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [18]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [32]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(5)

array([0.42873904, 0.56399135, 0.00089949, 0.27043839, 0.53010696])

In [40]:
np.random.randn(4,3)

array([[-0.61623854,  0.83260594, -0.22962212],
       [ 1.70178884,  1.69054664, -0.85597186],
       [-0.39694555,  0.40476625,  0.26728904],
       [ 0.25558543,  0.03476248,  0.91836003]])

In [44]:
np.random.randint(1,100,10)

array([57, 49, 74, 46, 97, 84, 40,  8, 54, 44])

# Numpy array indexing 

In [49]:
import numpy as np

In [59]:
arrayone = np.arange(11,21)

In [60]:
print(arrayone)

[11 12 13 14 15 16 17 18 19 20]


In [61]:
print (arrayone[1])

12


In [63]:
arrayone[1:6]

array([12, 13, 14, 15, 16])

In [65]:
arrayone[0:5]

array([11, 12, 13, 14, 15])

In [66]:
arrayone[5:]

array([16, 17, 18, 19, 20])

In [67]:
arrayone[:5]

array([11, 12, 13, 14, 15])

In [68]:
arrayone[5:] =100

In [69]:
arrayone

array([ 11,  12,  13,  14,  15, 100, 100, 100, 100, 100])

In [70]:
slice_of_arrayone = arrayone[5:]

In [72]:
slice_of_arrayone

array([100, 100, 100, 100, 100])

In [73]:
arrayone

array([ 11,  12,  13,  14,  15, 100, 100, 100, 100, 100])

In [74]:
arrayoneCopy = arrayone.copy()

In [75]:
arrayoneCopy

array([ 11,  12,  13,  14,  15, 100, 100, 100, 100, 100])

In [77]:
arrayoneCopy[:] = 99

In [78]:
arrayoneCopy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [79]:
arrayone

array([ 11,  12,  13,  14,  15, 100, 100, 100, 100, 100])

# Numpy Indexing and Selection

In [80]:
array_2d = np.array([[1,2,3],[10,20,30],[100,200,300]])

In [81]:
array_2d

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [82]:
array_2d[0][0]

1

In [87]:
array_2d[1][1]

20

In [88]:
array_2d[2][1]

200

In [89]:
array_2d[:2,1:]

array([[ 2,  3],
       [20, 30]])

In [95]:
array_2d[0:,:2]

array([[  1,   2],
       [ 10,  20],
       [100, 200]])

In [96]:
testarray = np.arange(1,10)

In [97]:
testarray 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
testarray > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [99]:
testarray < 5

array([ True,  True,  True,  True, False, False, False, False, False])

# Numpy Operation

In [101]:
arraynew = np.arange(0,11)

In [102]:
arraynew

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arraynew + arraynew

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [105]:
arraynew * arraynew

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
arraynew * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [108]:
arraynew / arraynew

C:\Users\suman\AppData\Local\Temp/ipykernel_10468/2927760884.py:1: RuntimeWarning: invalid value encountered in true_divide
  arraynew / arraynew


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [109]:
np.exp(arraynew)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [110]:
np.max(arraynew)

10

In [111]:
np.min(arraynew)

0

In [112]:
np.log(arraynew)

C:\Users\suman\AppData\Local\Temp/ipykernel_10468/3134120196.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arraynew)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])